version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - run: npm install
            - run: npm test
  build:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm build
  deploy:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm build

workflows:
  build-test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - hold:
          type: approval 
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
            - build
            - hold
          filters:
            branches:
              only:
                - master