version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws-ecs: circleci/aws-ecs@1.2.0

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  test:
    executor:
      name: node/default
    working_directory: ~/test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  build:
    executor:
      name: node/default
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  deploy:
    executor:
      name: node/default
    working_directory: ~/build
    steps:
      - run: npm install
      - run: npm build
      - add_ssh_keys:
          fingerprints:
          -   ${FINGERPRINTS}
      - run: scp -oStrictHostKeyChecking=no -r $CIRCLE_WORKING_DIRECTORY ${SERVER}:/home/ubuntu/meu-app/
      - sayhello:
          to: "Meu projeto"

workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - hold:
          type: approval 
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
            - build
            - hold
          filters:
            branches:
              only:
                - master
