version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - run: npm install
            - run: npm test
  hold:
    type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
    requires:
     - build-and-test
workflows:
    build-and-test:
      jobs:
        - build-and-test
